# server config
server:
  port: 8080

spring:
  # app config
  application:
    name: comment-management
  # db config
  # postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/cdb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    #initialization-mode: always
  # jpa config
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 2b0c542f8cc0e6bbbbe2307f102fc89e1d3f727177be6a93538f7216807a18d9
      expiration: 86400000 # 1 day
      refresh-token:
        expiration: 604800000 # 7 days

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

comments-mgmt:
  url:
    dev: localhost
    staging: stg.comments-management.com
    prod: prod.comments-management.com

# swagger ui
springdoc:
  swagger-ui:
    defaultModelsExpandDepth: 0
    docExpansion: none

security:
  whitelist:
    - /api/v1/auth/register/**
    - /api/v1/auth/login/**
    - /v3/api-docs/**
    - /swagger-ui/**
    - /swagger-ui.html
    - /actuator/**
